/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as TrackerRouteImport } from './routes/tracker'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AskIndexRouteImport } from './routes/ask.index'
import { Route as AskThreadIdRouteImport } from './routes/ask.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackerRoute = TrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AskIndexRoute = AskIndexRouteImport.update({
  id: '/ask/',
  path: '/ask/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskThreadIdRoute = AskThreadIdRouteImport.update({
  id: '/ask/$threadId',
  path: '/ask/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/doctor': typeof DoctorRoute
  '/history': typeof HistoryRoute
  '/tracker': typeof TrackerRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/': typeof AskIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/doctor': typeof DoctorRoute
  '/history': typeof HistoryRoute
  '/tracker': typeof TrackerRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask': typeof AskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/doctor': typeof DoctorRoute
  '/history': typeof HistoryRoute
  '/tracker': typeof TrackerRoute
  '/api/chat': typeof ApiChatRoute
  '/ask/$threadId': typeof AskThreadIdRoute
  '/ask/': typeof AskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/doctor'
    | '/history'
    | '/tracker'
    | '/api/chat'
    | '/ask/$threadId'
    | '/ask/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/doctor'
    | '/history'
    | '/tracker'
    | '/api/chat'
    | '/ask/$threadId'
    | '/ask'
  id:
    | '__root__'
    | '/'
    | '/assessment'
    | '/doctor'
    | '/history'
    | '/tracker'
    | '/api/chat'
    | '/ask/$threadId'
    | '/ask/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentRoute: typeof AssessmentRoute
  DoctorRoute: typeof DoctorRoute
  HistoryRoute: typeof HistoryRoute
  TrackerRoute: typeof TrackerRoute
  ApiChatRoute: typeof ApiChatRoute
  AskThreadIdRoute: typeof AskThreadIdRoute
  AskIndexRoute: typeof AskIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracker': {
      id: '/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof TrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/': {
      id: '/ask/'
      path: '/ask'
      fullPath: '/ask/'
      preLoaderRoute: typeof AskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask/$threadId': {
      id: '/ask/$threadId'
      path: '/ask/$threadId'
      fullPath: '/ask/$threadId'
      preLoaderRoute: typeof AskThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentRoute: AssessmentRoute,
  DoctorRoute: DoctorRoute,
  HistoryRoute: HistoryRoute,
  TrackerRoute: TrackerRoute,
  ApiChatRoute: ApiChatRoute,
  AskThreadIdRoute: AskThreadIdRoute,
  AskIndexRoute: AskIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
